name: Run tests

on:  
  push:
  pull_request:
    branches:
      - master

jobs:  
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install --force
      - run: npm test